#!/usr/local/bin/perl -w 
use strict;
use lib "/usr/local/gkb/modules";
use GKB::StableIdentifierDatabase;
use CGI qw(:standard);
use CGI::Carp 'fatalsToBrowser';
use GKB::FrontPage3;

my $stable = GKB::StableIdentifierDatabase->new();
my $browser = '/cgi-bin/instancebrowser?ID=';

my $CGI = CGI->new();

my $st_id = $CGI->param('ST_ID') || $CGI->param('STID') || handle_error('NO STABLE ID TO SEARCH');
$st_id =~ s/\.\d+$//;

my $db_id = $stable->db_id_from_stable_id($st_id);

# We have an ID, send to instance browser
if ($db_id) {
    my $url = "$browser$db_id";
    print $CGI->redirect($url);
}
else {
    handle_error("Unable to find a Reactome Instance for stable identifier $st_id");
}

exit 0;

sub handle_error {
    my ($error_message) = @_;

    my $front_page = GKB::FrontPage3->new("eventbrowser", "/stylesheet.css");
    my $header = $front_page->get_header();
    my $footer = $front_page->get_footer();

    print header, $header;
    print qq(<h1 CLASS="frontpage"><FONT COLOR="RED">Internal error</FONT></h1>\n);
    print qq(<h1><PRE>\n\n\n$error_message\n\n</PRE></h1>\n);
    print $footer;

    exit;
}
