#!/usr/local/bin/perl

use strict;
use lib "/usr/local/gkb/modules";
use CGI qw(:standard);
use GKB::DBAdaptor;
use GKB::PrettyInstance;
use GKB::WebUtils;
use GKB::Config;
use Data::Dumper;
use GKB::FrontPage3;

my $header = undef;
my $footer = undef;
my $enclosing_div_start = undef;
my $enclosing_div_end = undef;
my $reactome_version_num = "2";

my $front_page = GKB::FrontPage3->new("$PROJECT_NAME (instancebrowser)", "/stylesheet.css");
$header = $front_page->get_header();
$footer = $front_page->get_footer();
$enclosing_div_start = $front_page->get_enclosing_div_start();
$enclosing_div_end = $front_page->get_enclosing_div_end();

my $DBA;

my $CGI = CGI->new();

my $DB = $CGI->param('DB') || $GK_DB_NAME;
$CGI->param('DB', $DB);

eval {

$DBA = GKB::DBAdaptor->new
    (
     -dbname => $DB,
     -user   => $GK_DB_USER,
     -host   => $GK_DB_HOST,
     -pass   => $GK_DB_PASS,
     -port   => $GK_DB_PORT,
     -debug  => defined $CGI->param('DEBUG') ? $CGI->param('DEBUG') : undef 
     );

my $wu = GKB::WebUtils->new(-DBA => $DBA,
			    -CGI => $CGI,
			    -DEBUG => defined $CGI->param('DEBUG') ? $CGI->param('DEBUG') : undef
			    );

if (!(defined $header)) {
    print $wu->top_navigation_box;
    $wu->print_query_form;
}

$wu->urlmaker->script_name('/cgi-bin/instancebrowser');
$wu->omit_view_switch_link(1);

my $instances;
if ($CGI->param('CLASS')) {
    # Link from classbrowser
    $CGI->param('FORMAT') || $CGI->param('FORMAT','list');
    $instances = $DBA->fetch_all_class_instances_as_shells($CGI->param('CLASS'));
    do_header();
    $wu->print_view($instances,0);
} elsif ($CGI->param('ID')) {
    $instances = $wu->handle_query_form;
    if (@{$instances} == 1) {
	if ($instances->[0]->class eq 'Person') {
	    my $id = $CGI->param('ID');
	    print $CGI->redirect("/cgi-bin/author_contributions?DB_ID=$id");
	    exit;
	} 

	if (! $CGI->param('FORMAT')) {
	    $CGI->param('FORMAT','instancebrowser');
	}
    } else {
	if (! $CGI->param('FORMAT')) {
	    $CGI->param('FORMAT','list');
	}
    }
    do_header();
    $wu->print_view($instances);
} elsif ($CGI->param('SUBMIT')) {
    $instances = $wu->handle_query_form;
    if (! $CGI->param('FORMAT') && (@{$instances} == 1)) {
	$CGI->param('FORMAT','instancebrowser');
    }
    $wu->print_view($instances);
}

if (defined $enclosing_div_end) {
    print $enclosing_div_end;
}

if (!(defined $footer)) {
    print qq(<BR />\n), $wu->make_footer;
}

}; $@ && handle_error($@);

if (defined $footer) {
    print $footer;
} else {
    print $CGI->end_html;
}

$DBA && $DBA->db_handle->disconnect;

sub handle_error {
    print qq(<PRE>@_</PRE>);
    print qq(</TD></TR>\n</TABLE>\n);
}

sub do_header {
    print $CGI->header(-charset => 'UTF-8');
    if (defined $header) {
	print $header;
    } else {
    print $CGI->start_html(
	-style => {-src => '/stylesheet.css'},
	-title => "$PROJECT_NAME (instancebrowser)",
	-script => {-src => '/google.js'},
	);
    }

    if (defined $enclosing_div_start) {
	print $enclosing_div_start;
    }

}

