#!/usr/local/bin/perl

# The following block sets the script to pick up libraries from ../../modules.
# The point here is to avoid having the change 'use lib "/path/to/GKB/modules";'
# on different server setups.
BEGIN {
    my ($path) = $0 =~ /^(\S+)$/;
    my @a = split('/',$path);
    pop @a;
    if (@a && !$a[0]) {
	$#a = $#a - 2;
    } else {
	push @a, ('..','..');
    }
    push @a, 'modules';
    my $libpath = join('/', @a);
    unshift (@INC, $libpath);
}

use CGI qw(:standard);
use GKB::FrontPage3;
my $front_page = GKB::FrontPage3->new("header", "/stylesheet.css");
my $header = $front_page->get_header();

print header,$header;
