#!/usr/local/bin/perl -w -T

# The following block sets the script to pick up libraries from ../../modules.
# The point here is to avoid having the change 'use lib "/path/to/GKB/modules";'
# on different server setups.
BEGIN {
    my ($path) = $0 =~ /^(\S+)$/;
    my @a = split('/',$path);
    pop @a;
    if (@a && !$a[0]) {
	$#a = $#a - 2;
    } else {
	push @a, ('..','..');
    }
    push @a, 'modules';
    my $libpath = join('/', @a);
    unshift (@INC, $libpath);
}
#use lib "/tmp/libs/bioperl-1.0";
#use lib "/tmp/libs/my_perl_stuff";

use strict;
use GKB::WebUtils;
use GKB::Config;

eval {
    my $wu = GKB::WebUtils->new_from_cgi();

    my @tmp = $wu->cgi->param('ID');
    my @ids;
    foreach (@tmp) {
	if (/^(\d+)$/) {
	    push @ids, $1;
	}
    }
    @ids = sort {$a <=> $b}  @ids;

    my $basename = join('_', $PROJECT_NAME, @ids, $$);

    $wu->create_protege_project_wo_orthologues($basename,\@ids);

    print $wu->cgi->redirect("/img-tmp/$basename.tar.gz");
};
if ($@) {
    print <<__HERE__;
Content-Type: text/plain; charset=ISO-8859-1

$@
__HERE__
}
