#!/usr/local/bin/perl -w 

use strict;

use lib "/usr/local/gkb/modules";

use GKB::WebUtils;
use GKB::Config;

eval {
    my $wu = GKB::WebUtils->new_from_cgi();

    my @tmp = $wu->cgi->param('ID');
    my @ids;
    foreach (@tmp) {
	if (/^(\d+)$/) {
	    push @ids, $1;
	}
    }
    @ids = sort {$a <=> $b}  @ids;
	
    my $id = [$ids[0]];
    my $basename = join('_', $PROJECT_NAME, @$id);
    
    my $tarball = "/img-tmp/protege/$basename.tar.gz";
    unless (-z $tarball || ! -e $tarball) {
	$wu->create_protege_project_wo_orthologues($basename,$id);
    }
    
    print $wu->cgi->redirect($tarball);
};
if ($@) {
    print <<__HERE__;
Contentype: text/plain; charset=ISO-8859-1

$@
__HERE__
}
