#!/usr/local/bin/perl

umask(002);

use strict;
use lib '/usr/local/gkb/modules';
use CGI qw(:standard);
use GKB::DBAdaptor;
use GKB::PrettyInstance;
use GKB::WebUtils;
use GKB::Config;
use Data::Dumper;
use Carp;
use GKB::FrontPage3;


my $front_page = GKB::FrontPage3->new("$PROJECT_NAME (Table of contents)", "/stylesheet.css");
my $header = $front_page->get_header();
my $footer = $front_page->get_footer();
my $enclosing_div_start = $front_page->get_enclosing_div_start();
my $enclosing_div_end = $front_page->get_enclosing_div_end();


$NO_SCHEMA_VALIDITY_CHECK = 1;

my ($CGI,$DB,$WU,$DBA);

$CGI = CGI->new();
print $CGI->header(-charset => 'UTF-8');
eval {
    $WU = GKB::WebUtils->new_from_cgi(-CGI => $CGI);
    $WU->force_pwb_link(1);
    $DBA = $WU->dba;
    $WU->urlmaker->script_name('/cgi-bin/eventbrowser');

    if (defined $header) {
        print $header;
        print $enclosing_div_start;
    } else {
        print $CGI->start_html(
    	-style => {-src => '/stylesheet.css'},
    	-title => "$PROJECT_NAME: table of contents",
	-script => {-src => '/google.js'},
    	);
        print $WU->navigation_bar;
        $WU->print_simple_query_form;
    }
    create_TOC_if_necessary_and_print($WU,$CGI->param('DB'));
    if (defined $footer) {
        print $enclosing_div_end;
        print $footer;
    } else {
        print $WU->make_footer;
        print $CGI->end_html;  
    }
    $DBA && $DBA->db_handle->disconnect;
};
if ($@) {
    handle_error($@);
}

sub handle_error {
    print @_;
}

sub create_TOC_if_necessary_and_print {
    my ($wu,$db_name) = @_;
    my $dir_name = "$FRONTPAGE_IMG_DIR/$db_name";
    unless (-e $dir_name) {
		mkdir($dir_name) || confess("Can't create '$dir_name': $!");
    }
    my $file = "$dir_name/toc";
    unless (-e $file) {
		open (TOC, ">$file") || $wu->throw($!);
		my $tmp = select(TOC);
		$wu->print_TOC;
		close TOC;
		select($tmp);
    }
    open (TOC, $file) || $wu->throw($!);
    local $/ = undef;
    print <TOC>;
    close TOC;
}
