package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

/**
 * BlackBoxEvent generated by hbm2java
 */
@XmlRootElement
public class BlackBoxEvent extends ReactionlikeEvent {

    private Event templateEvent;
    private List<Event> hasEvent;

    public BlackBoxEvent() {
    }

    public Event getTemplateEvent() {
        return this.templateEvent;
    }

    public void setTemplateEvent(Event templateEvent) {
        this.templateEvent = templateEvent;
    }

    public List<Event> getHasEvent() {
        return hasEvent;
    }

    public void setHasEvent(List<Event> hasEvent) {
        this.hasEvent = hasEvent;
    }

    
}
