package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * EvidenceType generated by hbm2java
 */
@XmlRootElement
public class EvidenceType extends DatabaseObject {

    private String definition;
    private StableIdentifier stableIdentifier;

    public StableIdentifier getStableIdentifier() {
        return stableIdentifier;
    }

    public void setStableIdentifier(StableIdentifier stableIdentifier) {
        this.stableIdentifier = stableIdentifier;
    }

    public EvidenceType() {
    }

    public String getDefinition() {
        return this.definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

}
