package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * GenomeEncodedEntity generated by hbm2java
 */
@XmlRootElement
public class GenomeEncodedEntity extends PhysicalEntity {
    private Taxon species;

    public GenomeEncodedEntity() {
    }

    public Taxon getSpecies() {
        return species;
    }

    public void setSpecies(Taxon species) {
        this.species = species;
    }


}
