package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Ontology generated by hbm2java
 */
@XmlRootElement
public class Ontology extends DatabaseObject {

    private byte[] ontology;

    public Ontology() {
    }

    public Ontology(byte[] ontology) {
        this.ontology = ontology;
    }

    public byte[] getOntology() {
        return this.ontology;
    }

    public void setOntology(byte[] ontology) {
        this.ontology = ontology;
    }

}
