package org.reactome.core.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * PathwayCoordinates generated by hbm2java
 */
@XmlRootElement
public class PathwayCoordinates extends DatabaseObject {

    private Integer locatedEvent;
    private String locatedEventClass;
    private Integer maxX;
    private Integer maxY;
    private Integer minX;
    private Integer minY;

    public PathwayCoordinates() {
    }

    public Integer getLocatedEvent() {
        return this.locatedEvent;
    }

    public void setLocatedEvent(Integer locatedEvent) {
        this.locatedEvent = locatedEvent;
    }

    public String getLocatedEventClass() {
        return this.locatedEventClass;
    }

    public void setLocatedEventClass(String locatedEventClass) {
        this.locatedEventClass = locatedEventClass;
    }

    public Integer getMaxX() {
        return this.maxX;
    }

    public void setMaxX(Integer maxX) {
        this.maxX = maxX;
    }

    public Integer getMaxY() {
        return this.maxY;
    }

    public void setMaxY(Integer maxY) {
        this.maxY = maxY;
    }

    public Integer getMinX() {
        return this.minX;
    }

    public void setMinX(Integer minX) {
        this.minX = minX;
    }

    public Integer getMinY() {
        return this.minY;
    }

    public void setMinY(Integer minY) {
        this.minY = minY;
    }

}
