package org.reactome.core.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReactionCoordinates generated by hbm2java
 */
@XmlRootElement
public class ReactionCoordinates extends DatabaseObject {

    private Integer locatedEvent;
    private String locatedEventClass;
    private Integer locationContext;
    private String locationContextClass;
    private Integer sourceX;
    private Integer sourceY;
    private Integer targetX;
    private Integer targetY;

    public ReactionCoordinates() {
    }

    public Integer getLocatedEvent() {
        return this.locatedEvent;
    }

    public void setLocatedEvent(Integer locatedEvent) {
        this.locatedEvent = locatedEvent;
    }

    public String getLocatedEventClass() {
        return this.locatedEventClass;
    }

    public void setLocatedEventClass(String locatedEventClass) {
        this.locatedEventClass = locatedEventClass;
    }

    public Integer getLocationContext() {
        return this.locationContext;
    }

    public void setLocationContext(Integer locationContext) {
        this.locationContext = locationContext;
    }

    public String getLocationContextClass() {
        return this.locationContextClass;
    }

    public void setLocationContextClass(String locationContextClass) {
        this.locationContextClass = locationContextClass;
    }

    public Integer getSourceX() {
        return this.sourceX;
    }

    public void setSourceX(Integer sourceX) {
        this.sourceX = sourceX;
    }

    public Integer getSourceY() {
        return this.sourceY;
    }

    public void setSourceY(Integer sourceY) {
        this.sourceY = sourceY;
    }

    public Integer getTargetX() {
        return this.targetX;
    }

    public void setTargetX(Integer targetX) {
        this.targetX = targetX;
    }

    public Integer getTargetY() {
        return this.targetY;
    }

    public void setTargetY(Integer targetY) {
        this.targetY = targetY;
    }

}
