package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * ReactionVertex generated by hbm2java
 */
@XmlRootElement
public class ReactionVertex extends Vertex {

    private String pointCoordinates;

    public ReactionVertex() {
    }

    public String getPointCoordinates() {
        return this.pointCoordinates;
    }

    public void setPointCoordinates(String pointCoordinates) {
        this.pointCoordinates = pointCoordinates;
    }

}
