package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

/**
 * Reaction generated by hbm2java
 */
@XmlRootElement
public class Reaction extends ReactionlikeEvent {
    private Reaction reverseReaction;
    private String totalProt;
    private String maxHomologues;
    private String inferredProt;
    private List<Regulation> regulation;

    public Reaction() {
    }


    public List<Regulation> getRegulation() {
        return regulation;
    }

    public void setRegulation(List<Regulation> regulation) {
        this.regulation = regulation;
    }

    public String getTotalProt() {
        return this.totalProt;
    }

    public void setTotalProt(String totalProt) {
        this.totalProt = totalProt;
    }

    public String getMaxHomologues() {
        return this.maxHomologues;
    }

    public void setMaxHomologues(String maxHomologues) {
        this.maxHomologues = maxHomologues;
    }

    public String getInferredProt() {
        return this.inferredProt;
    }

    public void setInferredProt(String inferredProt) {
        this.inferredProt = inferredProt;
    }


    public Reaction getReverseReaction() {
        return reverseReaction;
    }


    public void setReverseReaction(Reaction reverseReaction) {
        this.reverseReaction = reverseReaction;
    }

}
