package org.reactome.core.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1


/**
 * ReferenceMolecule generated by hbm2java
 */
@XmlRootElement
public class ReferenceMolecule extends ReferenceEntity {
    private String atomicConnectivity;
    private String formula;

    public ReferenceMolecule() {
    }

    public String getAtomicConnectivity() {
        return atomicConnectivity;
    }

    public void setAtomicConnectivity(String atomicConnectivity) {
        this.atomicConnectivity = atomicConnectivity;
    }

    public String getFormula() {
        return formula;
    }

    public void setFormula(String formula) {
        this.formula = formula;
    }

}
