package org.reactome.core.model;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * ReferenceGeneProduct generated by hbm2java
 */
@XmlRootElement
public class ReferenceGeneProduct extends ReferenceSequence {
    private List<ReferenceDNASequence> referenceGene;
    private List<ReferenceRNASequence> referenceTranscript;

    public ReferenceGeneProduct() {
    }

    public List<ReferenceDNASequence> getReferenceGene() {
        return referenceGene;
    }

    public void setReferenceGene(List<ReferenceDNASequence> referenceGene) {
        this.referenceGene = referenceGene;
    }

    public List<ReferenceRNASequence> getReferenceTranscript() {
        return referenceTranscript;
    }

    public void setReferenceTranscript(List<ReferenceRNASequence> referenceTranscript) {
        this.referenceTranscript = referenceTranscript;
    }

    
}
