package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import org.gk.model.GKInstance;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * SequenceDomain generated by hbm2java
 */
@XmlRootElement
public class SequenceDomain extends Domain {

    private Integer endCoordinate;
    private GKInstance referenceEntity;
    private Integer startCoordinate;

    public SequenceDomain() {
    }

    public Integer getEndCoordinate() {
        return this.endCoordinate;
    }

    public void setEndCoordinate(Integer endCoordinate) {
        this.endCoordinate = endCoordinate;
    }

    public Integer getStartCoordinate() {
        return this.startCoordinate;
    }

    public void setStartCoordinate(Integer startCoordinate) {
        this.startCoordinate = startCoordinate;
    }

	public GKInstance getReferenceEntity() {
		return referenceEntity;
	}

	public void setReferenceEntity(GKInstance referenceEntity) {
		this.referenceEntity = referenceEntity;
	}
    
}
