package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * StableIdentifier generated by hbm2java
 */
@XmlRootElement
public class StableIdentifier extends DatabaseObject {

    private String identifier;
    private String identifierVersion;
    private Integer referenceDatabase;
    private String referenceDatabaseClass;

    public StableIdentifier() {
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getIdentifierVersion() {
        return this.identifierVersion;
    }

    public void setIdentifierVersion(String identifierVersion) {
        this.identifierVersion = identifierVersion;
    }

    public Integer getReferenceDatabase() {
        return this.referenceDatabase;
    }

    public void setReferenceDatabase(Integer referenceDatabase) {
        this.referenceDatabase = referenceDatabase;
    }

    public String getReferenceDatabaseClass() {
        return this.referenceDatabaseClass;
    }

    public void setReferenceDatabaseClass(String referenceDatabaseClass) {
        this.referenceDatabaseClass = referenceDatabaseClass;
    }

}
