package org.reactome.core.model;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * Summation generated by hbm2java
 */
@XmlRootElement
public class Summation extends DatabaseObject {

    private String text;
    private List<Publication> literatureReference;

    public Summation() {
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public List<Publication> getLiteratureReference() {
        return literatureReference;
    }

    public void setLiteratureReference(List<Publication> literatureReference) {
        this.literatureReference = literatureReference;
    }
    

}
