package org.reactome.core.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * VertexSearchableTerm generated by hbm2java
 */
@XmlRootElement
public class VertexSearchableTerm extends PathwayDiagramItem {

    private Integer providerCount;
    private String searchableTerm;
    private Integer species;
    private String speciesClass;
    private Integer vertexCount;

    public VertexSearchableTerm() {
    }

    public Integer getProviderCount() {
        return this.providerCount;
    }

    public void setProviderCount(Integer providerCount) {
        this.providerCount = providerCount;
    }

    public String getSearchableTerm() {
        return this.searchableTerm;
    }

    public void setSearchableTerm(String searchableTerm) {
        this.searchableTerm = searchableTerm;
    }

    public Integer getSpecies() {
        return this.species;
    }

    public void setSpecies(Integer species) {
        this.species = species;
    }

    public String getSpeciesClass() {
        return this.speciesClass;
    }

    public void setSpeciesClass(String speciesClass) {
        this.speciesClass = speciesClass;
    }

    public Integer getVertexCount() {
        return this.vertexCount;
    }

    public void setVertexCount(Integer vertexCount) {
        this.vertexCount = vertexCount;
    }

}
