package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Vertex generated by hbm2java
 */
@XmlRootElement
public class Vertex extends DatabaseObject {

    private Integer height;
    private Integer pathwayDiagram;
    private String pathwayDiagramClass;
    private Integer representedInstance;
    private String representedInstanceClass;
    private Integer width;
    private Integer x;
    private Integer y;

    public Vertex() {
    }

    public Integer getHeight() {
        return this.height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getPathwayDiagram() {
        return this.pathwayDiagram;
    }

    public void setPathwayDiagram(Integer pathwayDiagram) {
        this.pathwayDiagram = pathwayDiagram;
    }

    public String getPathwayDiagramClass() {
        return this.pathwayDiagramClass;
    }

    public void setPathwayDiagramClass(String pathwayDiagramClass) {
        this.pathwayDiagramClass = pathwayDiagramClass;
    }

    public Integer getRepresentedInstance() {
        return this.representedInstance;
    }

    public void setRepresentedInstance(Integer representedInstance) {
        this.representedInstance = representedInstance;
    }

    public String getRepresentedInstanceClass() {
        return this.representedInstanceClass;
    }

    public void setRepresentedInstanceClass(String representedInstanceClass) {
        this.representedInstanceClass = representedInstanceClass;
    }

    public Integer getWidth() {
        return this.width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getX() {
        return this.x;
    }

    public void setX(Integer x) {
        this.x = x;
    }

    public Integer getY() {
        return this.y;
    }

    public void setY(Integer y) {
        this.y = y;
    }

}
