package GKB::Config_Orthomcl;

use strict;

use vars qw(@ISA @EXPORT %orthomcl %entrez);

use Exporter();
@ISA=qw(Exporter);


%orthomcl = ('ath' => {'name' => ['Arabidopsis thaliana'],
		       'refdb' => {'dbname' => ['TIGR'],
				   'url' => 'http://www.tigr.org',
				   'access' => 'http://www.tigr.org/tigr-scripts/euk_manatee/shared/ORF_infopage.cgi?db=ath1&orf=###ID###'},
		       'group' => 'Fungi/Plants',
		       'rank' => 46}, #these are non-sequential numbers, just to allow easy insertion of new species if needed
	     'osa' => {'name' => ['Oryza sativa'],
		       'refdb' => {'dbname' => ['TIGR osa'],
				   'url' => 'http://www.tigr.org',
#				   'access' => 'http://www.tigr.org/tigr-scripts/euk_manatee/shared/ORF_infopage.cgi?db=osa1r5&orf=###ID###'
			       },
		       'group' => 'Fungi/Plants',
		       'rank' => 47},
	     'cel' => {'name' => ['Caenorhabditis elegans'],
		       'refdb' => {'dbname' => ['Wormbase'],
				   'url' => 'http://www.wormbase.org',
				   'access' => 'http://www.wormbase.org/db/gene/gene?name=###ID###'},
		       'group' => 'Metazoan',
		       'rank' => 26},
	     'ddi' => {'name' => ['Dictyostelium discoideum'],
		       'refdb' => {'dbname' => ['Dictybase'],
				   'url' => 'http://dictybase.org',
				   'access' => 'http://dictybase.org/db/cgi-bin/gene_page.pl?dictybaseid=###ID###'},
		       'group' => 'Eukaryotes',
		       'rank' => 66},
	     #'access' => 'http://dictybase.org/db/cgi-bin/feature_page.pl?dictybaseid=###ID###'}},
	     'dme' => {'name'  => ['Drosophila melanogaster'],
		       'refdb' => {'dbname' => ['Flybase'],
				   'url' => 'http://www.flybase.net',
				   'access' => 'http://flybase.net/.bin/fbidq.html?###ID###'},
		       'group' => 'Metazoan',
		       'rank' => 22},
	     'eco' => {'name' => ['Escherichia coli'],
		       'refdb' => \%entrez,
		       'group' => 'Eubacteria',
		       'rank' => 85,
		       'prokaryote' => 1},
	     'hsa' => {'name' => ['Homo sapiens'],
		       'refdb' => {'dbname' => ['UniProt']},
		       'group' => 'Human',
		       'rank' => 10,
		       'ensmap' => 1, #species that are represented in Ensembl and for which mapping from ENSP to UniProt is needed
		       'altdb' => {'dbname' => ['ENSEMBL', 'ENSEMBL_Homo_sapiens_PROTEIN'],
				   'url' => 'http://www.ensembl.org/Homo_sapiens',
				   'access' => 'http://www.ensembl.org/Homo_sapiens/protview?peptide=###ID###&db=core',
				   'altid' => 'ENSP'}},
	     'mja' => {'name' => ['Methanococcus jannaschii'],
		       'refdb' => \%entrez,
		       'group' => 'Archaea',
		       'rank' => 77,
		       'prokaryote' => 1},
	     'mmu' => {'name' => ['Mus musculus'],
		       'refdb' => {'dbname' => ['UniProt']},
		       'group' => 'Vertebrate',
		       'rank' => 12,
		       'ensmap' => 1,
		       'altdb' => {'dbname' => ['ENSEMBL', 'ENSEMBL_Mus_musculus_PROTEIN'],
				   'url' => 'http://www.ensembl.org/Mus_musculus',
				   'access' => 'http://www.ensembl.org/Mus_musculus/protview?peptide=###ID###&db=core',
				   'altid' => 'ENSMUSP'}},
	     'pfa' => {'name' => ['Plasmodium falciparum'],
		       'refdb' => {'dbname' => ['PlasmoDB'],
				   'url' => 'http://plasmodb.org',
				   'access' => 'http://plasmodb.org/plasmodb/servlet/sv?page=gene&source_id=###ID###'},
		       'group' => 'Eukaryotes',
		       'rank' => 68},
	     'sce' => {'name' => ['Saccharomyces cerevisiae'],
		       'refdb' => {'dbname' => ['SGD', 'Saccharomyces Genome Database'],
				   'url' => 'http://www.yeastgenome.org',
				   'access' => 'http://db.yeastgenome.org/cgi-bin/locus.pl?locus=###ID###'},
		       'group' => 'Fungi/Plants',
		       'rank' => 34},
	     'spo' => {'name' => ['Schizosaccharomyces pombe'],
		       'refdb' => {'dbname' => ['GeneDB'],
				   'url' => 'http://www.genedb.org/genedb/pombe',
				   'access' => 'http://www.genedb.org/genedb/Search?organism=pombe&name=###ID###'},
		       'group' => 'Fungi/Plants',
		       'rank' => 37},
	     'sso' => {'name' => ['Sulfolobus solfataricus'],
		       'refdb' => \%entrez,
		       'group' => 'Archaea',
		       'rank' => 75,
		       'prokaryote' => 1},
	     'tni' => {'name' => ['Tetraodon nigroviridis'],
		       'refdb' => {'dbname' => ['ENSEMBL', 'ENSEMBL_Tetraodon_nigroviridis_PROTEIN'],
				   'url' => 'http://www.ensembl.org/Tetraodon_nigroviridis',
#				   'access' => 'http://apr2005.archive.ensembl.org/Tetraodon_nigroviridis/protview?peptide=###ID###'},
				   'access' => 'http://www.ensembl.org/Tetraodon_nigroviridis/Transcript/Protein?db=core;p=###ID###'},
		       'group' => 'Vertebrate',
		       'rank' => 18},
	     'gga' => {'name' => ['Gallus gallus'],
		       'refdb' => {'dbname' => ['ENSEMBL', 'ENSEMBL_Gallus_gallus_PROTEIN'],
				   'url' => 'http://www.ensembl.org/Gallus_gallus',
#				   'access' => 'http://apr2005.archive.ensembl.org/Gallus_gallus/protview?peptide=###ID###'},
				   'access' => 'http://www.ensembl.org/Gallus_gallus/Transcript/Protein?db=core;p=###ID###'},
		       'group' => 'Vertebrate',
		       'rank' => 16},
	     'rno' => {'name' => ['Rattus norvegicus'],
		       'refdb' => {'dbname' => ['ENSEMBL', 'ENSEMBL_Rattus_norvegicus_PROTEIN'],
				   'url' => 'http://www.ensembl.org/Rattus_norvegicus',
#				   'access' => 'http://apr2005.archive.ensembl.org/Rattus_norvegicus/protview?peptide=###ID###',
				   'access' => 'http://www.ensembl.org/Rattus_norvegicus/Transcript/Protein?db=core;p=###ID###',
			#	   'altid' => 'ENSRNOP'
			       },
		       #'refdb' => {'dbname' => ['UniProt']},
		       #'ensmap' => 1, #species that are represented in Ensembl and for which mapping from ENSP to UniProt is needed
		       'group' => 'Vertebrate',
		       'rank' => 14},
	     'cne' => {'name' => ['Cryptococcus neoformans'],
	     		# cne may be the wrong abbreviation
		       'refdb' => {'dbname' => ['TIGR cna'],
				   'url' => 'http://www.tigr.org/tdb/e2k1/cna1/',
				   'access' => 'http://www.tigr.org/tigr-scripts/euk_manatee/shared/ORF_infopage.cgi?db=cna1&orf=###ID###'
		       },
		       'group' => 'Fungi/Plants',
		       'rank' => 32},
	     'ncr' => {'name' => ['Neurospora crassa'],
		       'refdb' => {'dbname' => ['BROAD'],
				   'url' => 'http://www.broad.mit.edu/annotation/fungi/neurospora_crassa_7',
				   'access' => 'http://www.broad.mit.edu/cgi-bin/annotation/fungi/neurospora_crassa_3/findfeatures.cgi?FEATURETYPES=ANNOTATED_GENE&page=showfeatures&Search=Submit&GENELOCUS=###ID###'},
		       'group' => 'Fungi/Plants',
		       'rank' => 36},
	     'syn' => {'name' => ['Synechococcus sp.'],
		       'refdb' => \%entrez,
		       'group' => 'Eubacteria',
		       'rank' => 93,
		       'prokaryote' => 1},
	     'mtu' => {'name' => ['Mycobacterium tuberculosis'],
		       'refdb' => \%entrez,
		       'group' => 'Eubacteria',
		       'rank' => 96,
		       'prokaryote' => 1},
	     'ehi' => {'name' => ['Entamoeba histolytica'],
	     		# ehi may be the wrong abbreviation
		       'refdb' => {'dbname' => ['TIGR eha'],
				   'url' => 'http://www.tigr.org/tdb/e2k1/eha1/',
				   'access' => 'http://www.tigr.org/tigr-scripts/euk_manatee/shared/ORF_infopage.cgi?db=eha1&orf=###ID###'
		       },
		       'group' => 'Eukaryotes',
		       'rank' => 63},
	     'cme' => {'name' => ['Cyanidioschyzon merolae'],
		       'refdb' => {'dbname' => ['CME Genome Project'],
				   'url' => 'http://merolae.biol.s.u-tokyo.ac.jp',
				   'access' => 'http://merolae.biol.s.u-tokyo.ac.jp/db/search.cgi?keywords=###ID###'},
		       'group' => 'Eukaryotes',
		       'rank' => 42},
	     'tps' => {'name' => ['Thalassiosira pseudonana'],
		       'refdb' => {'dbname' => ['JGI'],
				   'url' => 'http://genome.jgi-psf.org/thaps1/thaps1.home.html',
				   'access' => 'http://genome.jgi-psf.org/cgi-bin/dispGeneModel?db=thaps1&tid=###ID###'},
		       'group' => 'Eukaryotes',
		       'rank' => 44}
	     );





%entrez = ('dbname' => ['Entrez'],
	   'url' => 'http://www.ncbi.nlm.nih.gov/gquery/gquery.fcgi',
	   'access' => 'http://www.ncbi.nlm.nih.gov/entrez/viewer.fcgi?db=protein&val=###ID###');


@EXPORT = qw(%orthomcl %entrez);



