package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

/**
 * CandidateSet generated by hbm2java
 */
@XmlRootElement
public class CandidateSet extends EntitySet {
    private List<PhysicalEntity> hasCandidate;

    public CandidateSet() {
    }

    public List<PhysicalEntity> getHasCandidate() {
        return hasCandidate;
    }

    public void setHasCandidate(List<PhysicalEntity> hasCandidate) {
        this.hasCandidate = hasCandidate;
    }

}
