package org.reactome.core.model;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * PositiveRegulation generated by hbm2java
 */
@XmlRootElement
public class PositiveRegulation extends Regulation {


    public PositiveRegulation() {
    }

}
