package org.reactome.core.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated Jul 8, 2011 1:48:55 PM by Hibernate Tools 3.4.0.CR1

/**
 * SimpleEntity generated by hbm2java
 */
@XmlRootElement
public class SimpleEntity extends PhysicalEntity {
    // Because a bug in the data model, this attribute is multiple valued.
    // However, it should be single valued. Here is the correct version.
    private ReferenceMolecule referenceEntity;
    private Species species;

    public SimpleEntity() {
    }

    public ReferenceMolecule getReferenceEntity() {
        return referenceEntity;
    }

    public void setReferenceEntity(ReferenceMolecule referenceEntity) {
        this.referenceEntity = referenceEntity;
    }

    public Species getSpecies() {
        return species;
    }

    public void setSpecies(Species species) {
        this.species = species;
    }

}
